name: 'TailwindCSS build on demand'
description: 'Installes then builds tailwindcss via GitHub Actions for example for GitHub Pages'
author: Balla Botond
branding:
  color: green
  icon: 'code'
inputs:
  input:
    description: 'path of input.css'
    required: true
    default: 'src/input.css'
  output:
    description: 'path of output.css'
    required: true
    default: 'src/output.css'
  params:
    description: 'addtional tailwind params'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
