name: 'Generate Tailwind CSS'
description: 'Creates Tailwind CSS CSS Files'
author: 'Zoey <zoey@z0ey.de>'
branding:
  color: green
  icon: arrow-down-circle
inputs:
  input:
    description: 'path of input.css'
    required: true
    default: 'src/input.css'
  output:
    description: 'path of output.css'
    required: true
    default: 'src/output.css'
  plugins:
    description: 'tailwind plugins'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
